[build]
  publish = "."  # Deploy from the root folder
  command = "echo 'No build command needed for static site'"

[[plugins]]
  package = "netlify-plugin-prerender-spa"
  [plugins.inputs]
    source = "."  # Plugin reads files from root
    minifyHTMLOpts = true
    routes = ["/", "/about", "/services", "/contact"]